### ISSUE TITLE
Apenas fontes no repositório

### ISSUE THREAD

**Issue by kyriosdata** [weinersilva/i-2018#1]
- Remova do repositório os arquivos .class e os diretórios que são gerados, ou seja, artefatos derivados dos fontes. Em geral não fazem parte do repositório que se concentra no código fonte.
- Renomeie os packages para algo como com.github.weinersilva.integracao, por exemplo. Trata-se de um nome único.

**Comment by weinersilva** [comment]
feito em 23/04
