### ISSUE TITLE
Estratégia da implementação "confusa"

### ISSUE THREAD

**Issue by kyriosdata** [weinersilva/i-2018#2]
- Não consegui compreender a estratégia do código em https://github.com/weinersilva/i-2018/blob/master/atividadeSupervisionadas_01-12032018/src/atividadeSupervisionadas02/Principal.java? Parece-me que há uma compreensão equivocada dos métodos empregados. São empregados laços?

**Comment by weinersilva** [comment]
feito em 23/04
